#!/bin/bash
echo 'total 40
drwxrwxr-x 2 vagrant vagrant 4096 Mar  7 17:06 .
drwxrwxr-x 6 vagrant vagrant 4096 Mar  7 09:50 ..
-rwxrw-r-- 1 vagrant vagrant   32 Mar  7 10:56 0-hello_world
-rwxrw-r-- 1 vagrant vagrant   29 Mar  7 11:02 1-confused_smiley
-rwxrw-r-- 1 vagrant vagrant   35 Mar  7 11:08 2-hellofile
-rwxrw-r-- 1 vagrant vagrant   53 Mar  7 11:10 3-twofiles
-rwxrw-r-- 1 vagrant vagrant   36 Mar  7 11:41 4-lastlines
-rwxrw-r-- 1 vagrant vagrant   37 Mar  7 11:41 5-firstlines
-rwxrw-r-- 1 vagrant vagrant   38 Mar  7 11:53 6-third_line
-rwxrw-r-- 1 vagrant vagrant  626 Mar  7 17:02 8-cwd_state' > ls_cwd_content
