#!/usr/bin/env bash
# script that installs and configures HAproxy on my lb-01 server acting as load balancer

sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
yes enter | sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy

# the load balancer's configuration
echo -e "\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 28140-web-01 44.210.86.178:80 check\n\tserver 28140-web-02 44.200.174.223:80 check" >> /etc/haproxy/haproxy.cfg

sudo service rsyslog restart
sudo service haproxy restart