#!/usr/bin/env bash
# script that generates a MySQL dump of all databases and creates a compressed archive out of it.
mysqldump -u root -p"$1" --opt --events --all-databases > backup.sql
tar czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
