#!/usr/bin/env bash
# script that sets port to 80
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-available/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart
