#!/usr/bin/env bash
# script that displays the content of the file "/etc/passwd"; only username, user id and home directory path for the user
while read l; do
	paste -d: <(echo "$l" | cut -d ":" -f1) <(echo "$l" | cut -d ":" -f4) <(echo "$l" | cut -d ":" -f6)
done < "/etc/passwd"
