#!/usr/bin/env bash
# configures nginx to be run by user nginx
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
su - nginx -c "sed -i 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart" 2&> /dev/null
